ccfit_app/urls.py
from django.conf.urls import url
from ccfit_app import views
from django.contrib.auth import views as auth_views

# Down below are all the routes for the project
app_name = 'ccfit'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r"login/$", views.LoginView,name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"edit_profile/$", views.EditProfile.as_view(), name="edit_profile"),
    url(r"password/$", views.PasswordsChangeView.as_view(template_name='ccfit_app/change_password.html'), name="change_password"),
    url(r"edit_profile_page/(?P<pk>\d+)", views.EditProfilePageView.as_view(), name="edit_profile_page"),
    url(r"password_sucess/$", views.password_sucess, name="password_sucess"),
    url("create_profile_page/$", views.CreateProfilePageView.as_view(), name="create_profile_page"),
    url(r"booking_page/$", views.BookingPage, name="booking_page"),
    url(r'booking_page/session/', views.Validate_date, name='validates'),
    url(r'workout/$', views.WorkoutView.as_view(), name='workout'),
    url(r'workout/verification/(?P<session>\d)', views.Check_Booking_workout, name='check_booking_workout'),
    url(r'workout/verification/', views.Check_Booking_workout, name='check_booking_workout'),
    url(r'workout/confirmation/', views.Confirmation_Booking, name='confirmation_booking'),
    url(r'pilates/$', views.PilatesView.as_view(), name='pilates'),
    url(r'pilates/verification/(?P<session>\d)', views.Check_Booking_pilates, name='check_booking_pilates'),
    url(r'pilates/verification/', views.Check_Booking_pilates, name='check_booking_pilates'),
    url(r'yoga/$', views.YogaView.as_view(), name='yoga'),
    url(r'yoga/verification/(?P<session>\d)', views.Check_Booking_yoga, name='check_booking_yoga'),
    url(r'yoga/verification/', views.Check_Booking_yoga, name='check_booking_yoga'),
    url(r'spin/$', views.SpinView.as_view(), name='spin'),
    url(r'spin/verification/(?P<session>\d)', views.Check_Booking_spin, name='check_booking_spin'),
    url(r'spin/verification/', views.Check_Booking_spin, name='check_booking_spin'),
    url(r'jump/$', views.JumpView.as_view(), name='jump'),
    url(r'jump/verification/(?P<session>\d)', views.Check_Booking_jump, name='check_booking_jump'),
    url(r'jump/verification/', views.Check_Booking_jump, name='check_booking_jump'),
    url(r"signup/$", views.create_user, name="signup"),
    url(r'allUsers/', views.UsersListView.as_view(), name='all_users'),
    url(r'management/(?P<pk>\d+)', views.UsersUpdateView.as_view(), name='update_user'),
    url(r'check_classes/session/', views.Validate_date_check, name='validates_check'),
    url(r"check_classes/$", views.CheckingPage, name="check_classes"),
    url(r'check_classes/change/(?P<class_number>\d)', views.ClassesCountView, name='classes_count'),
    url(r'class/(?P<session>\d)', views.Check_Class_Amount, name='check_class_amount'),
    url(r'my_bookings/', views.MyBookings, name='my_bookings'),
    url(r'pdf_view/', views.PDF.as_view(), name="pdf_view"),
    url(r'pdf_download/', views.DownloadPDF.as_view(), name="pdf_download"),
    url(r'payment/(?P<type>\d)', views.Payment, name="payment"),
    url(r'payment_request/', views.Payment_request, name="payment_request"),
    url(r'invoices/', views.InvoiceListView.as_view(), name="invoices"),
    url(r'invoice_user/(?P<pk>\d+)', views.InvoiceUser.as_view(), name="invoice_user"),
    url(r'status/(?P<pk>\d+)', views.MarkPaid, name="mark_paid"),
    url(r'send_invoice/(?P<pk>\d+)', views.SendInvoice, name="send_invoice"),

]

ccfit_project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from ccfit_app import views
from django.urls import path

# Main urls routes file
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'ccfit/', include('ccfit_app.urls',namespace='ccfit_app')),
    path(r'ccfit/', include('django.contrib.auth.urls')),
    path('', include('ccfit_app.urls')),
]

ccfit_app/forms.py
from django import forms
from ccfit_app.models import UserProfileInfo, Workout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


# The following two models are responsible for the
# date field on the booking sessions page
class DateInput(forms.DateInput):
    input_type = 'date'

class ExampleForm(forms.Form):
    my_date_field = forms.DateField(widget=DateInput)


# Form
# class WorkoutForm(forms.ModelForm):
#     class Meta:
#         model = Workout
#         fields = [
#                 'date',
#                 'email_user',
#                 'session_number',
#         ]

# The following 5 forms are used all for users but in
# different files
class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=50)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

    class Meta:
        model = get_user_model()
        fields = ('username','first_name','last_name','email', 'password1', 'password2')

# Form also for the signup page
class ProfilePageForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('nickname', 'gender', 'birth_date', 'address1', 'address2', 'county', 'country', 'prefix', 'phone', 'membership')


class EditProfileForm(UserChangeForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)


    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name','email')


class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(required=True, max_length=100)
    last_name = forms.CharField(required=True, max_length=100)

    class Meta:
        fields=('email','first_name','last_name', 'password1', 'password2')
        model = get_user_model()


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = 'email Address'


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = [
                'type',
                'active'
            ]
    def __init__(self, *args, **kwargs):
        super(UserProfileInfoForm, self).__init__(*args, **kwargs)
        self.fields['type'].initial = 'USER'
        self.fields['type'].widget = forms.HiddenInput()
        self.fields['active'].initial = 'INACTIVE'
        self.fields['active'].widget = forms.HiddenInput()


class UserUpdateForm(UserCreationForm):

    class Meta:
        fields=['email']
        model = get_user_model()


# Form used so the admin can manage the users
class UserProfileInfoFormUsers(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = [
                'type',
                'active',
                'nickname',
                'gender',
                'birth_date',
                'address1',
                'address2',
                'county',
                'country',
                'prefix',
                'phone',
            ]
    def __init__(self, *args, **kwargs):
        super(UserProfileInfoFormUsers, self).__init__(*args, **kwargs)
        self.fields['type'].initial = 'USER'
        self.fields['active'].initial = 'INACTIVE'

ccfit_app/views.py
from django.shortcuts import render, redirect, get_object_or_404, redirect
from .models import Workout, UserProfileInfo, Pilates, Yoga, Spin, Jump, User, MaxSession, Invoice
from django.contrib.auth.decorators import login_required
from . import forms
from django.views import generic
from ccfit_app.forms import SignUpForm, EditProfileForm, ProfilePageForm, ExampleForm, UserProfileInfoForm, UserCreateForm, UserUpdateForm, UserProfileInfoFormUsers
from django.contrib.auth import login, logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import CreateView, UpdateView, TemplateView, ListView, View
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from datetime import datetime, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from .decorators import user_all_classes, user_workout, admin_only, admin_teacher_only
from django.utils.decorators import method_decorator
from django.template.loader import get_template
from django.contrib.staticfiles import finders
from xhtml2pdf import pisa
from django.conf import settings
import stripe
import time
import os


# Down below are all the functions and classes where the
# logic for the whole website is kept


stripe.api_key = os.environ.get('STRIPE_PRIVATE_KEY')


# Function responsible process the payment wheather is
# and enrollment fee or monthly payment
@login_required
def Payment_request(request):
	# Enrollment fee
	num_max_users = MaxSession.objects.get(key='CCFIT')
	if request.session['type_payment'] == '1':
		amount = num_max_users.enrolment
		description = 'enrolment fee'
	else:
		# Monthly payment
		user = UserProfileInfo.objects.get(email=request.user)
		if user.active == 'ALL CLASSES':
			amount = num_max_users.a_classes
		elif user.active == 'WORKOUT ONLY':
			amount = num_max_users.w_only
		else:
		    print('Inactive User')
		description = 'monthly payment'

	# Executed when the submit is pressed
	if request.method == 'POST':
		customer = stripe.Customer.create(
			email=request.POST['email'],
			name=request.POST['nickname'],
			source=request.POST['stripeToken']
		)
		charge = stripe.Charge.create(
			customer=customer,
			amount=amount*100,
			currency='eur',
			description=description,
		)

		#Updating status and data for that users payment
		if request.session['type_payment'] == '1':
			verify_enrollment = Invoice.objects.get(email=request.user, type='ENROLMENT FEE')
			today_date = datetime.today().strftime('%Y-%m-%d')
			today_date_object = datetime.strptime(today_date, '%Y-%m-%d').date()
			future_30days = str(today_date_object + timedelta(days = 30))
			future_30days_DATE = datetime.strptime(future_30days, '%Y-%m-%d').date()
			verify_enrollment.from_date = today_date_object
			verify_enrollment.to_date = future_30days_DATE
			verify_enrollment.status = 'PAID'
			verify_enrollment.save()
			email_user = str(request.user)
			message = 'Dear ' + str(verify_enrollment.email) + '\nThank you for trusting CCFIT to be your gym. \nThis is your receipt for paying €' +  str(verify_enrollment.cost) + ' regarding the ' + verify_enrollment.type
			send_mail('CCFIT Invoice: ' + str(verify_enrollment.from_date) + ' - ' + str(verify_enrollment.to_date), message, 'ccfitgym@gmail.com', [email_user], fail_silently=False)
		else:
			# this if is for the monthly payment
			verify_enrollment = Invoice.objects.filter(email=request.user, type='MONTHLY PAYMENT', status='REQUESTED').order_by('from_date')
			if verify_enrollment.exists():
				for course in verify_enrollment:
					verify_enrollment_unique = Invoice.objects.get(pk=course.pk)
					verify_enrollment_unique.status = 'PAID'
					verify_enrollment_unique.save()
					email_user = str(request.user)
					message = 'Dear ' + str(verify_enrollment_unique.email) + '\nThank you for trusting CCFIT to be your gym. \nThis is your receipt for paying €' +  str(verify_enrollment_unique.cost) + ' regarding the ' + verify_enrollment_unique.type
					send_mail('CCFIT Invoice: ' + str(verify_enrollment_unique.from_date) + ' - ' + str(verify_enrollment_unique.to_date), message, 'ccfitgym@gmail.com', [email_user], fail_silently=False)
					break
	request.session['confirm_message'] = 'PAID'
	return HttpResponseRedirect(reverse_lazy('ccfit:index'))
	# return render(request, 'ccfit_app/index.html')


# Function for the button in the generate invoice page
# to mark the payment as paid when the user doesnt pay
# by stripe
@login_required
@admin_only
def MarkPaid(request, pk):
	verify_enrollment = Invoice.objects.get(pk=pk)
	verify_enrollment.status = 'PAID'
	verify_enrollment.save()
	return HttpResponseRedirect(reverse_lazy('ccfit:invoices'))


# Function for the button in the generate invoice page
# send the invoice to the user when generated
@login_required
@admin_only
def SendInvoice(request, pk):
	verify_enrollment = Invoice.objects.get(pk=pk)
	verify_enrollment.status = 'REQUESTED'
	verify_enrollment.save()
	email_user = str(verify_enrollment.email)
	message = 'Dear ' + str(verify_enrollment.email) + '\nThank you for trusting CCFIT to be your gym. \nYour invoice for this month is now availabe.' + ' \nCheck on https://ccfitgym.herokuapp.com/ to pay'
	# Send email
	send_mail('CCFIT Invoice: ' + str(verify_enrollment.from_date) + ' - ' + str(verify_enrollment.to_date), message, 'ccfitgym@gmail.com', [email_user], fail_silently=False)
	return HttpResponseRedirect(reverse_lazy('ccfit:invoices'))

# Funcion that processes the payment and
# shows the info for the user before paying
@login_required
def Payment(request, type):
	request.session['confirm_message'] = ''
	request.session['type_payment'] = type
	user = UserProfileInfo.objects.get(email=request.user)
	# Checking if is enrollment fee or montly payment
	if request.session['type_payment'] == '1':
		description = 'ENROLMENT FEE'
		invoice = Invoice.objects.get(email=request.user, type='ENROLMENT FEE')
		from_date = invoice.from_date
		to_date = invoice.to_date
		year = invoice.year
		cost = invoice.cost
		pk = invoice.pk
	else:
		# If for the monthly payment
		description = 'MONTHLY PAYMENT'
		invoice = Invoice.objects.filter(email=request.user, type='MONTHLY PAYMENT', status='REQUESTED').order_by('from_date')
		if invoice.exists():
			for course in invoice:
				from_date = course.from_date
				to_date = course.to_date
				year = course.year
				cost = course.cost
				pk = course.pk
				break
	context = {'pk': pk, 'nickname':user.nickname, 'email': request.user, 'from_date':from_date, 'to_date': to_date, 'cost':cost,'subscription':description, 'year':year }
	return render(request, 'ccfit_app/payment.html', context)


# Invoice page
@method_decorator(admin_only, name='dispatch')
class InvoiceListView(LoginRequiredMixin, ListView):
	template_name = "ccfit_app/invoices.html"
	model = Invoice
	context_object_name = "invoices"


	def get_queryset(self):
		print("FAZ A BUSCA PADRAO DO FILTRO")
		email = self.request.GET.get('search')
		print(email, 'thats the email')
		object_list = self.model.objects.all()
		print(object_list)
		if email:
			object_list = object_list.filter(email__contains=email)
		return object_list


# This function allows the functions of creation of the pdf
# to have images and other resources
def link_callback(uri, rel):
        result = finders.find(uri)
        if result:
                if not isinstance(result, (list, tuple)):
                        result = [result]
                result = list(os.path.realpath(path) for path in result)
                path=result[0]
        else:
                sUrl = settings.STATIC_URL        # Typically /static/
                sRoot = settings.STATIC_ROOT      # Typically /home/userX/project_static/
                mUrl = settings.MEDIA_URL         # Typically /media/
                mRoot = settings.MEDIA_ROOT       # Typically /home/userX/project_static/media/

                if uri.startswith(mUrl):
                        path = os.path.join(mRoot, uri.replace(mUrl, ""))
                elif uri.startswith(sUrl):
                        path = os.path.join(sRoot, uri.replace(sUrl, ""))
                else:
                        return uri

        # make sure that file exists
        if not os.path.isfile(path):
                raise Exception(
                        'media URI must start with %s or %s' % (sUrl, mUrl)
                )
        return path

# Main function that creates the pdf
def render_to_pdf(template_src, context_dict={}):
	template = get_template(template_src)
	html  = template.render(context_dict)
	response = HttpResponse(content_type='application/pdf')
	response['Content-Disposition'] = 'filename="Invoice.pdf"'
	pisa_status = pisa.CreatePDF(html, dest=response, link_callback=link_callback)
	if pisa_status.err:
		return HttpResponse('we had some erros')
	return response


# Function that calls the main function from the generate invoice
class InvoiceUser(LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		new = Invoice.objects.filter(pk=self.kwargs['pk'])
		if new.exists():
			for unit in new:
				user = UserProfileInfo.objects.get(email=unit.email)
				d1 = {'email': unit.email, 'from_date': str(unit.from_date), 'to_date': str(unit.to_date),
						'cost': unit.cost, 'type': unit.type, 'subscription': user.active,
						'nickname': user.nickname, 'gender': user.gender, 'address_one': user.address1,
						'address_two': user.address2, 'county': user.county, 'country': user.country,
						 'prefix': user.prefix, 'phone': user.phone}
		# Calls the main function to create the pdf
		pdf = render_to_pdf('ccfit_app/pdf/invoice_template.html', d1)
		response = HttpResponse(pdf, content_type='application/pdf')
		content = 'filename="report.pdf"'
		response['Content-Disposition'] = content
		return response

ccfit_app/templates/ccfit_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../../static/css/style.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;500;600;900&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    <title>ccfit</title>
  </head>
  <body>
    <div class="container">
      <section class="box-home">
        <nav class="navbar">
          <a href="{% url 'ccfit_app:index' %}" class="logo"><img src="../../../static/img/logo-small.png" alt="" class="navbar__logo"></a>

          {% if user.is_authenticated %}
            <a href="{% url 'ccfit_app:edit_profile' %}" class="navbar__button">Edit Settings</a>
            {% if user.userprofileinfo.id %}
            <a href="{% url 'ccfit_app:edit_profile_page' user.userprofileinfo.id %}" class="navbar__button">Edit Profile</a>
            {% else %}
            <a href="{% url 'ccfit_app:create_profile_page' %}" class="navbar__button">Create Profile Page</a>
            {% endif %}
          {% else %}
              <a href="{% url 'ccfit_app:login' %}" class="navbar__button">Login</a>
                <a href="{% url 'ccfit_app:signup' %}" class="btn btn-simple" class="navbar__button">Sign Up</a>
          {% endif %}
          <a href="{% url 'ccfit_app:logout' %}" class="navbar__button">Logout</a>

            {% if nickname == None %}
              <div class="navbar__user-name">CCfit Gym</div>
            {% else %}
              <div class="navbar__user-name">Welcome {{ nickname }}</div>
            {% endif %}


          {% if type != None %}
            {% if type == 'USER' %}
              <!-- {% if status == 'GENERATE' %} -->
              <!-- <a href="{% url 'ccfit_app:payment' type=1 %}">Pay enrollment fee</a> -->
              <!-- {% endif %} -->

              <div class="navbar__user">{{ type }}</div>


            {% elif type == 'TEACHER'  %}
              <div class="navbar__user">{{ type }}</div>
              <!-- <a href="{% url 'ccfit_app:check_classes' %}">Check classes</a> -->
            {% else  %}
              <!-- <a href="{% url 'ccfit_app:check_classes' %}">Check classes</a>
              <a href="{% url 'ccfit_app:invoices' %}">Generate Invoice</a> -->
              <div class="navbar__user">{{ type }}</div>
            {% endif %}
          {% endif %}

          <!-- <div class="navbar__user">user</div> -->
        </nav>
      </section>

      {% block body_block %}
      {% endblock %}

    </div>
    <!-- <div class="footer">
      <div class="footer__button footer__button-1">About us</div>
      <div class="footer__button footer__button-2">Privacy</div>
      <div class="footer__button footer__button-3">Join us!</div>
      <div class="footer__button footer__button-4">Careers</div>
      <div class="footer__copyright">&copy; Copyright - All rights reserved - 2021</div>
    </div> -->
  </body>
</html>

ccfit_app/templates/ccfit_app/index.html
<!DOCTYPE html>
{% extends 'ccfit_app/base.html' %}
{% block body_block %}

  {% if request.session.confirm_message %}
  <div class="confirmed">
    Payment successfuly completed!
  </div>
  {% endif %}

    {% if not registration %}
    <div class="message">
      Welcome to CCfit! Please finish your registration by clicking on 'Edit Profile' to generate the Enrolment Fee.
    </div>
    {% endif %}
    <div class="book">
      {% if type == 'TEACHER'   %}
        <a href="{% url 'ccfit_app:check_classes' %}" class="book__card book__card-1">Check classes</a>
        {% elif type == 'ADMINISTRATOR'  %}
          <a href="{% url 'ccfit_app:check_classes' %}" class="book__card book__card-1">Check classes</a>
          <a href="{% url 'ccfit_app:invoices' %}" class="book__card book__card-2">Generate Invoice</a>
      {% endif %}

      {% if user.is_superuser %}
        <a href="{% url 'ccfit_app:all_users' %}" class="book__card book__card-3">Manage users</a>
      {% endif %}

      {% if type == 'USER'   %}
        {% if registration %}
          {% if status == 'PAID' %}
            <a href="{% url 'ccfit_app:booking_page' %}" class="book__card book__card-1">Book Session</a>
          {% endif %}
        {% endif %}
      {% endif %}

      {% if type == 'USER' %}
        <a href="{% url 'ccfit_app:my_bookings' %}" class="book__card book__card-2">My Bookings</a>
        {% if status_MP == 'REQUESTED' %}
          <a href="{% url 'ccfit_app:payment' type=2 %}" class="book__card book__card-3">Monthly Payment</a>
        {% endif %}
      {% endif %}

      {% if type == 'USER' %}
        {% if status == 'GENERATE' %}
          <a href="{% url 'ccfit_app:payment' type=1 %}" class="book__card book__card-3">Enrolment fee</a>
        {% endif %}
      {% endif %}
    </div>

    <div class="main__title">Join us now!</div>
    <div class="main">
      <div class="card card-1">
        <img src="../../../static/img/workout.jpg" alt="" class="card__img">
        <div class="card__name">Workout</div>
      </div>
      <div class="card card-2">
        <img src="../../../static/img/pilates.jpg" alt="" class="card__img">
        <div class="card__name">Pilates</div>
      </div>
      <div class="card card-3">
        <img src="../../../static/img/jump.jpg" alt="" class="card__img">
        <div class="card__name">Jump</div>
      </div>
      <div class="card card-4">
        <img src="../../../static/img/spinner.jpg" alt="" class="card__img">
        <div class="card__name">Spin</div>
      </div>
      <div class="card card-5">
        <img src="../../../static/img/yoga.jpg" alt="" class="card__img">
        <div class="card__name">Yoga</div>
      </div>
      <div class="card card-6">
        <img src="../../../static/img/dance.jpg" alt="" class="card__img">
        <div class="card__name">Dance</div>
      </div>
    </div>
{% endblock %}

ccfit_app/templates/ccfit_app/login.html
<!DOCTYPE html>
{% load widget_tweaks %}
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../../static/css/style.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;500;600;900&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    <title>ccfit</title>
  </head>
  <body>
    <div class="container">
      <section class="box-signup">
        <form class="user"  method="post" id="loginForm">
          <div class="box">
            <img src="../../../static/img/logo-small.png" alt="" class="navbar__logo">
            <h2 class="heading-2">Sign in</h2>
            {% csrf_token %}
            <input type="email" name="email" id="email" class="box__input" placeholder="E-mail" required>
            <input type="password" name="password" id="password" class="box__input" placeholder="Password" required>

            <button type="submit"  class="btn">Access</button>
            <input type="button" class="btn-2" value="Sign Up" onclick="location.href='{% url 'ccfit_app:signup' %}';">
          </div>
        </form>
      </section>
    </div>
    <div class="footer">
      <div class="footer__button footer__button-1">About us</div>
      <div class="footer__button footer__button-2">Privacy</div>
      <div class="footer__button footer__button-3">Join us!</div>
      <div class="footer__button footer__button-4">Careers</div>
      <div class="footer__copyright">&copy; Copyright - All rights reserved - 2021</div>
    </div>
  </body>
</html>

ccfit_app/templates/ccfit_app/pilates.html
<!DOCTYPE html>
{% extends 'ccfit_app/base.html' %}
{% block body_block %}

<script>
  var perfEntries = performance.getEntriesByType("navigation");
  if (perfEntries[0].type === "back_forward") {
    location.reload(true);
  }
</script>

<div class="box-count">
  <div class="count-classes">
      <h2 class="heading-2">Booking confirmation</h2>
    <input class="box__input date__classes" type="date" id="date-input" value="{{date}}" disabled required />


    {% if session_1.expired %}
      <div class="line">
        <div class="line__time">{{session_1.start}} - {{session_1.finish}}</div>
        <div class="line__count">
          <button  class="line__btn" type="button" onclick="location.href='{% url 'ccfit_app:check_booking_pilates' session=1 %}'" name="button" {% if session_1.enable %} disabled {% endif %}>{{session_1.status}}</button>
        </div>
      </div>
    {% endif %}

    {% if session_2.expired %}
      <div class="line">
        <div class="line__time">{{session_2.start}} - {{session_2.finish}}</div>
        <div class="line__count">
          <button  class="line__btn" type="button" onclick="location.href='{% url 'ccfit_app:check_booking_pilates' session=2 %}'" name="button" {% if session_2.enable %} disabled {% endif %}>{{session_2.status}}</button>
        </div>
      </div>
    {% endif %}

    {% if session_3.expired %}
      <div class="line">
        <div class="line__time">{{session_3.start}} - {{session_3.finish}}</div>
        <div class="line__count">
          <button  class="line__btn" type="button" onclick="location.href='{% url 'ccfit_app:check_booking_pilates' session=3 %}'" name="button" {% if session_3.enable %} disabled {% endif %}>{{session_3.status}}</button>
        </div>
      </div>
    {% endif %}

    {% if session_4.expired %}
      <div class="line">
        <div class="line__time">{{session_4.start}} - {{session_4.finish}}</div>
        <div class="line__count">
          <button  class="line__btn" type="button" onclick="location.href='{% url 'ccfit_app:check_booking_pilates' session=4 %}'" name="button" {% if session_4.enable %} disabled {% endif %}>{{session_4.status}}</button>
        </div>
      </div>
    {% endif %}

    {% if session_5.expired %}
      <div class="line">
        <div class="line__time">{{session_5.start}} - {{session_5.finish}}</div>
        <div class="line__count">
          <button  class="line__btn" type="button" onclick="location.href='{% url 'ccfit_app:check_booking_pilates' session=5 %}'" name="button" {% if session_5.enable %} disabled {% endif %}>{{session_5.status}}</button>
        </div>
      </div>
    {% endif %}

    {% if session_6.expired %}
      <div class="line">
        <div class="line__time">{{session_6.start}} - {{session_6.finish}}</div>
        <div class="line__count">
          <button  class="line__btn" type="button" onclick="location.href='{% url 'ccfit_app:check_booking_pilates' session=6 %}'" name="button" {% if session_6.enable %} disabled {% endif %}>{{session_6.status}}</button>
        </div>
      </div>
    {% endif %}

{% endblock %}